In [3]:
import numpy as np

print(np.__version__)


2.4.6


In [5]:
# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4])
print("1D Array:", array_1d)  # Expected Output: 1D Array: [1 2 3 4]

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2D Array:\n", array_2d)
# Expected Output:
# 2D Array:
# [[1 2 3 4]
#  [5 6 7 8]]

# Array attributes
print("Shape:", array_2d.shape)  # Expected Output: Shape: (2, 3) - 2 rows and 3 columns
print("Size:", array_2d.size)   # Expected Output: Size: 6 - Total 6 elements
print("Data Type:", array_2d.dtype)  # Expected Output: Data Type: int64 (or similar, depending on system)

1D Array: [1 2 3 4]
2D Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Size: 8
Data Type: int64


In [7]:
img = [[[1, 2, 3, 4], 
       [5, 6, 7, 8],
       [1, 2, 3, 4]],

       [[1, 2, 3, 4], 
       [5, 6, 7, 8],
       [1, 2, 3, 4]],

       [[1, 2, 3, 4], 
       [5, 6, 7, 8],
       [1, 2, 3, 4]]
       ]

ar3d = np.array(img)
print(ar3d.shape)


(3, 3, 4)


In [ ]:
# (depth, rows, columns)

In [10]:
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("2D Array:\n", array_2d)

array_2d[0,2]

a = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(a[0][2])

2D Array:
 [[1 2 3 4]
 [5 6 7 8]]
3


In [11]:
print(img)


[[[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]], [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]], [[1, 2, 3, 4], [5, 6, 7, 8], [1, 2, 3, 4]]]


In [ ]:
print(ar3d[1,1,3])  # depth, row, column


8


In [ ]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9,10,11,12]])
print(b[1,0:]) # going tot he end of the row

[5 6 7 8]


In [16]:
print(b[:3,1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [17]:
print(b[0:,0])  # only first column

[1 5 9]


In [21]:
print(b[:2,1])


[2 6]


In [ ]:
print(b)

print(b[:2,1:3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [25]:
print(b[0:,0::2]) # skips over 

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [26]:
res = np.random.randint(0, 1000, 14)
print(res)

[985 560 551 404 381 486 935 236 718 543 816 168 535 217]


In [29]:
ages = np.random.normal(45, 20, 100)
print(ages)


[ 36.42808963  11.06429787  54.30354431  57.13414446  35.77159625
  27.16965958   2.75179186  30.85482723  51.47173571  57.11999722
  65.12207713  36.07823008  36.44768336   9.58178698  19.24144066
  57.2142627   41.41888497  45.67894132  64.23602838  81.49108969
  37.68172561  77.14502719  42.86762712  44.96301307  36.45977114
  57.03302556   5.58015152  65.13047494  38.41300736  61.61900269
  36.55140894  58.05559112  71.08680761  35.71932553  61.23997914
  70.79301698  35.65487976  69.64864231   0.44569358  51.71618535
  46.6533608   33.66950692  17.63776286  27.39450929  65.77078282
  37.21225144  10.83422448  56.93245625  24.33251343  34.02438319
  59.20999705  43.8047378   22.30508658  41.994052    40.94770372
  38.7529774   74.01892077  42.63722914  55.21195514  71.67529155
  45.91506875  35.60749172  34.01434454  59.66553872  47.40659797
  55.05387456  72.33070614   9.39831268  25.20691816  43.5710878
  35.13743549  59.78404975  79.00902917  44.16702277  24.95128369
  55.957253

In [ ]:
np.random.seed(32)  # not working to setthe initial point of calculating the random function


In [93]:
x = np.array([1, 2, 3, 4, 5, 6, 7])
new = np.random.permutation(x)
new


array([3, 1, 7, 4, 2, 6, 5])

In [45]:
for i in range(12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [46]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [51]:
x = np.arange(24).reshape((2,3,4))

print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [52]:
x[0,1,2] = 92 # change value is a specific cell in an array
print(x)


[[[ 0  1  2  3]
  [ 4  5 92  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
x[0,2,1:3] = -1
print(x)


[[[ 0  1  2  3]
  [ 4  5 92  7]
  [ 8 -1 -1 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [55]:
y = np.array([1,2,3,4,5,6,7])
y[2:5] = np.array([99,77,66])
y

array([ 1,  2, 99, 77, 66,  6,  7])

In [ ]:
x[0,0::2,0::2] = -42 # replcae certain values in an array
x

array([[[-42,   1, -42,   3],
        [  4,   5,  92,   7],
        [-42,  -1, -42,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [ ]:
print(x>=20)
print(x[x>=20])
x[x>=20] = 20

x

[[[False False False False]
  [False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]]
[]


array([[[-42,   1, -42,   3],
        [  4,   5,  20,   7],
        [-42,  -1, -42,  11]],

       [[ 12,  13,  14,  15],
        [ -1,  17,  18,  19],
        [ 20,  20,  20,  20]]])

In [76]:
x[1,1,0] = -1
x


array([[[ 99,   1, 100,   3],
        [  4,   5,  20,   7],
        [101, 102, 103,  11]],

       [[ 12,  13,  14,  15],
        [ -1,  17,  18,  19],
        [ 20,  20,  20,  20]]])

In [81]:
x[x<0] = [ 99, 100, 101, 102, 103, 104]

ValueError: NumPy boolean array indexing assignment cannot assign 6 input values to the 1 output values where the mask is true