In [1]:
import numpy as np

# ---------Exercise 1 -------------Creating a 1D NumPy array containg numbers 0-9

array = np.arange(0,10)
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# ---------Exercise 2 -------------Type Conversion and Array Operations

my_list = [3.14, 2.17, 0, 1, 2]

my_int_array = np.array([int(x) for x in my_list])

my_int_array

array([3, 2, 0, 1, 2])

In [3]:
# ---------Exercise 3 ------------- Working with Multi-Dimensional Arrays

array3x3 = np.arange(1,10).reshape((3,3))

array3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# ---------Exercise 4 -------------  Creating Multi-Dimensional Array with Random Numbers

numbers = np.random.normal(0.5, 0.2, 20)
array4x5 = np.array([round(x, 2)for x in numbers]).reshape((4,5))
array4x5

array([[ 0.71,  0.58,  0.76,  0.24,  0.25],
       [ 0.53,  0.75,  0.54, -0.  ,  0.35],
       [ 0.74,  0.28,  0.18,  0.53,  0.26],
       [ 0.5 ,  0.47,  0.42,  0.41,  0.62]])

In [46]:
# ---------Exercise 5 -------------  Indexing Arrays

# Select the second row from a given 2D NumPy array.

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

print(array[1,])


[20 21 22 23 24]


In [47]:
# ---------Exercise 6 -------------  Reversing elements

# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

array = np.arange(0,10)

rev_array = array[::-1]

rev_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# ---------Exercise 7 -------------  Identity Matrix

# Create a 4x4 identity matrix using NumPy.

numbers = np.random.choice([0.,1.], size=16)

array4x4 = np.array(numbers).reshape((4,4))
array4x4

array([[0., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 1., 0., 1.],
       [1., 0., 1., 1.]])

In [68]:
# ---------Exercise 8 -------------  Simple Aggregate Funcs

array = np.arange(0,10)

x = array.sum()
y = array.mean()
print(f"The Sum: {x}, the Average: {y}")

The Sum: 45, the Average: 4.5


In [71]:
# ---------Exercise 9 -------------  Create Array and Change its Structure


array = np.arange(1,21)

array4x5 = np.array(array).reshape((4,5))

array4x5


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [80]:
# ---------Exercise 10 -------------  Conditional Selection of Values


array = np.arange(1,11,2)

array

array([1, 3, 5, 7, 9])